version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: extrato
      POSTGRES_USER: extrato_user
      POSTGRES_PASSWORD: extrato_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql